stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - minikube
  script:
    - eval $(minikube docker-env)
    - docker build -t my-node-app:latest .

deploy:
  stage: deploy
  tags:
    - minikube
  script:
    - kubectl apply -f k8s/